services:
  - type: web
    name: ai-image-detector
    env: node
    plan: free
    buildCommand: |
      # Install Node.js dependencies
      npm install
      
      # Install Python and dependencies
      apt-get update && apt-get install -y python3 python3-pip python3-venv
      python3 -m pip install --upgrade pip
      python3 -m pip install numpy opencv-python pillow scikit-image scipy tensorflow
      
      # Build the application
      npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: ai-detector-disk
      mountPath: /tmp
      sizeGB: 1